
trigger: 
- main

pool: 
  vmImage: ubuntu-latest

variables:
  builConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(builConfiguration)
  displayName: 'dotnet build $(builConfiguration)' 